- name: Create docker_php directory
  file:
    path: "{{ user.home }}/docker/docker_php"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy Dockerfile
  template:
    src: ./Dockerfile.j2
    dest: "{{ user.home }}/docker/docker_php/Dockerfile"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Create supervisord directory
  file:
    path: "{{ user.home }}/docker/docker_php/etc/supervisor/conf.d/"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy supervisord.conf
  copy:
    src: ./etc/supervisor/conf.d/supervisord.conf
    dest: "{{ user.home }}/docker/docker_php/etc/supervisor/conf.d/supervisord.conf"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Create php directory
  file:
    path: "{{ user.home }}/docker/docker_php/usr/local/etc/php/"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory

- name: Copy php.ini
  copy:
    src: ./usr/local/etc/php/php.ini
    dest: "{{ user.home }}/docker/docker_php/usr/local/etc/php/php.ini"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Create etc directories
  file:
    path: "{{ item }}"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550
    state: directory
  with_items:
    - "{{ dir.shared.sites_enabled }}"
    - "{{ dir.shared.certs }}"
    - "{{ dir.shared.private }}"

- name: Copy site conf
  template:
    src: "./etc/nginx/sites-enabled/php.webdev.conf.j2"
    dest: "{{ dir.shared.sites_enabled }}/{{ domains.php_app }}.conf"
    owner: "{{ user.name }}"
    group: docker
    mode: 0550

- name: Generate an OpenSSL private key.
  openssl_privatekey:
    path: "{{ dir.shared.private }}/{{ domains.php_app }}.key"
  notify:
    - Chown private

- name: Generate an OpenSSL CSR.
  openssl_csr:
    path: "{{ dir.shared.private }}/{{ domains.php_app }}.csr"
    privatekey_path: "{{ dir.shared.private }}/{{ domains.php_app }}.key"
    common_name: "{{ domains.php_app }}"
  notify:
    - Chown private

- name: Create openssl certificate
  openssl_certificate:
    path: "{{ dir.shared.certs }}/{{ domains.php_app }}.crt"
    privatekey_path: "{{ dir.shared.private }}/{{ domains.php_app }}.key"
    csr_path: "{{ dir.shared.private }}/{{ domains.php_app }}.csr"
    provider: selfsigned
  notify:
    - Chown certs

- name: Create php app directory
  file:
    path: "{{ dir.php_app }}"
    owner: "{{ user.name }}"
    group: docker
    mode: 0750
    state: directory