FROM php:7.3-fpm

USER root

RUN apt-get update
RUN apt-get -y install openssl \
                       git \
                       zip \
                       supervisor

# --- Install composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

# --- Setup user
RUN groupadd --gid {{ user.gid }} {{ user.group }}
RUN useradd {{ user.name }} --uid {{ user.uid }} -m -g {{ user.group }}
RUN echo "{{ user.password }}:{{ user.password }}" | chpasswd

# --- Configure supervisord
COPY ./etc/supervisor/conf.d/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
#RUN chown -R {{ user.name }}:{{ user.name }} /var/log/supervisor/
#RUN chmod -R 0750 /var/log/supervisor/

RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

RUN sed -i 's/www-data/{{ user.name }}/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/www-data/{{ user.name }}/g' /usr/local/etc/php-fpm.d/www.conf.default

COPY ./usr/local/etc/php/php.ini /usr/local/etc/php/php.ini
RUN chmod 0775 /usr/local/etc/php/php.ini

WORKDIR {{ dir.php_app }}

#USER {{ user.name }}

EXPOSE 9000 9001

CMD [ "supervisord", "-n" ]