FROM php:7.3-fpm

USER root

RUN apt-get update

# --- Copy nginx file
RUN mkdir -p /etc/nginx/sites-enabled/
COPY ./etc/nginx/sites-enabled/php.webdev.conf /etc/nginx/sites-enabled/{{ domain }}.conf

# --- Install composer
RUN curl -sS https://getcomposer.org/installer | php
RUN mv composer.phar /usr/local/bin/composer

# --- Install and configure supervisord
RUN apt-get -y install supervisor
COPY ../files/etc/supervisor /etc/supervisor/conf.d/supervisord.conf

# --- Setup user
RUN groupadd --gid {{ group_gid }} {{ user_group }}
RUN useradd {{ user_name }} --uid {{ user_uid }} -m -g {{ user_group }}
RUN echo "{{ user_password }}:{{ user_password }}" | chpasswd

RUN pecl install xdebug
RUN docker-php-ext-enable xdebug

RUN sed -i 's/www-data/{{ user_name }}/g' /usr/local/etc/php-fpm.d/www.conf
RUN sed -i 's/www-data/{{ user_name }}/g' /usr/local/etc/php-fpm.d/www.conf.default

COPY ./usr/local/etc/php/php.ini /usr/local/etc/php/php.ini
RUN chmod 0775 /usr/local/etc/php/php.ini

WORKDIR {{ php_app_dir }}

USER {{ user_name }}

EXPOSE 9000 9001

CMD [ "supervisord", "-n" ]